package br.galante.webapp.futebol.model;

// Generated 27/10/2010 11:46:42 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", catalog = "futebol")
public class Grupo implements java.io.Serializable {

	private Integer idGrupo;
	private String descricao;
	private Set<Participante> participantes = new HashSet<Participante>(0);

	public Grupo() {
	}

	public Grupo(String descricao) {
		this.descricao = descricao;
	}

	public Grupo(String descricao, Set<Participante> participantes) {
		this.descricao = descricao;
		this.participantes = participantes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGrupo", unique = true, nullable = false)
	public Integer getIdGrupo() {
		return this.idGrupo;
	}
	
	@Transient
	public Integer getId(){
		return this.idGrupo;
	}

	public void setIdGrupo(Integer idGrupo) {
		this.idGrupo = idGrupo;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Participante> getParticipantes() {
		return this.participantes;
	}

	public void setParticipantes(Set<Participante> participantes) {
		this.participantes = participantes;
	}

}
