package br.galante.webapp.futebol.model;

// Generated 27/10/2010 11:46:42 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Local generated by hbm2java
 */
@Entity
@Table(name = "local", catalog = "futebol")
public class Local implements java.io.Serializable {

	private Integer idLocal;
	private String descricao;
	private Set<Partida> partidas = new HashSet<Partida>(0);

	public Local() {
	}

	public Local(String descricao) {
		this.descricao = descricao;
	}

	public Local(String descricao, Set<Partida> partidas) {
		this.descricao = descricao;
		this.partidas = partidas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLocal", unique = true, nullable = false)
	public Integer getIdLocal() {
		return this.idLocal;
	}

	@Transient
	public Integer getId(){
		return this.idLocal;
	}
	
	public void setIdLocal(Integer idLocal) {
		this.idLocal = idLocal;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "local")
	public Set<Partida> getPartidas() {
		return this.partidas;
	}

	public void setPartidas(Set<Partida> partidas) {
		this.partidas = partidas;
	}

}
