package br.galante.webapp.futebol.model;

// Generated 27/10/2010 11:46:42 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "futebol")
public class Pais implements java.io.Serializable {

	private Integer idPais;
	private String nome;
	private String sigla;
	private Set<Time> times = new HashSet<Time>(0);

	public Pais() {
	}

	public Pais(String nome, String sigla) {
		this.nome = nome;
		this.sigla = sigla;
	}

	public Pais(String nome, String sigla, Set<Time> times) {
		this.nome = nome;
		this.sigla = sigla;
		this.times = times;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPais", unique = true, nullable = false)
	public Integer getIdPais() {
		return this.idPais;
	}
	
	@Transient
	public Integer getId(){
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "sigla", nullable = false, length = 3)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Time> getTimes() {
		return this.times;
	}

	public void setTimes(Set<Time> times) {
		this.times = times;
	}

}
