package br.galante.webapp.futebol.model;

// Generated 27/10/2010 11:46:42 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "partida", catalog = "futebol")
public class Partida implements java.io.Serializable {

	private Integer idPartida;
	private Participante participanteByIdVisitante;
	private Local local;
	private Participante participanteByIdMandante;
	private Integer golsMandante;
	private Integer golsVisitante;
	private TipoPartida tipoPartida;
	private Date dataPartida;

	public Partida() {
		this.participanteByIdMandante = new Participante();
		this.participanteByIdVisitante = new Participante();
		this.local = new Local();
		this.tipoPartida = new TipoPartida();
		this.dataPartida = new Date();
	}

	public Partida(Participante participanteByIdVisitante,
			Participante participanteByIdMandante) {
		this.participanteByIdVisitante = participanteByIdVisitante;
		this.participanteByIdMandante = participanteByIdMandante;
	}

	public Partida(Participante participanteByIdVisitante, Local local,
			Participante participanteByIdMandante, Integer golsMandante,
			Integer golsVisitante, TipoPartida tipoPartida, Date dataPartida) {
		this.participanteByIdVisitante = participanteByIdVisitante;
		this.local = local;
		this.participanteByIdMandante = participanteByIdMandante;
		this.golsMandante = golsMandante;
		this.golsVisitante = golsVisitante;
		this.tipoPartida = tipoPartida;
		this.dataPartida = dataPartida;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPartida", unique = true, nullable = false)
	public Integer getIdPartida() {
		return this.idPartida;
	}
	
	@Transient
	public Integer getId(){
		return this.idPartida;
	}

	public void setIdPartida(Integer idPartida) {
		this.idPartida = idPartida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVisitante", nullable = false)
	public Participante getParticipanteByIdVisitante() {
		return this.participanteByIdVisitante;
	}

	public void setParticipanteByIdVisitante(
			Participante participanteByIdVisitante) {
		this.participanteByIdVisitante = participanteByIdVisitante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLocal")
	public Local getLocal() {
		return this.local;
	}

	public void setLocal(Local local) {
		this.local = local;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMandante", nullable = false)
	public Participante getParticipanteByIdMandante() {
		return this.participanteByIdMandante;
	}

	public void setParticipanteByIdMandante(
			Participante participanteByIdMandante) {
		this.participanteByIdMandante = participanteByIdMandante;
	}

	@Column(name = "golsMandante")
	public Integer getGolsMandante() {
		return this.golsMandante;
	}

	public void setGolsMandante(Integer golsMandante) {
		this.golsMandante = golsMandante;
	}

	@Column(name = "golsVisitante")
	public Integer getGolsVisitante() {
		return this.golsVisitante;
	}

	public void setGolsVisitante(Integer golsVisitante) {
		this.golsVisitante = golsVisitante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoPartida", nullable = false)
	public TipoPartida getTipoPartida() {
		return tipoPartida;
	}

	public void setTipoPartida(TipoPartida tipoPartida) {
		this.tipoPartida = tipoPartida;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataPartida", length = 19)
	public Date getDataPartida() {
		return this.dataPartida;
	}

	public void setDataPartida(Date dataPartida) {
		this.dataPartida = dataPartida;
	}

}
