package br.galante.webapp.futebol.model;

// Generated 27/10/2010 11:46:42 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Time generated by hbm2java
 */
@Entity
@Table(name = "time", catalog = "futebol")
public class Time implements java.io.Serializable {

	private Integer idTime;
	private Pais pais;
	private String nome;
	private String abreviacao;
	private String sigla;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Participante> participantes = new HashSet<Participante>(0);

	public Time() {
		this.pais = new Pais();
		
	}

	public Time(Pais pais, String nome, String abreviacao, String sigla) {
		this.pais = pais;
		this.nome = nome;
		this.abreviacao = abreviacao;
		this.sigla = sigla;
	}

	public Time(Pais pais, String nome, String abreviacao, String sigla,
			Set<Usuario> usuarios, Set<Participante> participantes) {
		this.pais = pais;
		this.nome = nome;
		this.abreviacao = abreviacao;
		this.sigla = sigla;
		this.usuarios = usuarios;
		this.participantes = participantes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTime", unique = true, nullable = false)
	public Integer getIdTime() {
		return this.idTime;
	}

	public void setIdTime(Integer idTime) {
		this.idTime = idTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "abreviacao", nullable = false, length = 45)
	public String getAbreviacao() {
		return this.abreviacao;
	}

	public void setAbreviacao(String abreviacao) {
		this.abreviacao = abreviacao;
	}

	@Column(name = "sigla", nullable = false, length = 3)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "time")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "time")
	public Set<Participante> getParticipantes() {
		return this.participantes;
	}

	public void setParticipantes(Set<Participante> participantes) {
		this.participantes = participantes;
	}

}
