package br.galante.webapp.futebol.model;

// Generated 27/10/2010 11:46:42 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipopartida generated by hbm2java
 */
@Entity
@Table(name = "tipopartida", catalog = "futebol")
public class TipoPartida implements java.io.Serializable {

	private Integer idTipoPartida;
	private String descricao;
	private Integer qtdPartidas;

	public TipoPartida() {
	}

	public TipoPartida(String descricao) {
		this.descricao = descricao;
	}

	public TipoPartida(String descricao, Integer qtdPartidas) {
		this.descricao = descricao;
		this.qtdPartidas = qtdPartidas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTipoPartida", unique = true, nullable = false)
	public Integer getIdTipoPartida() {
		return this.idTipoPartida;
	}

	public void setIdTipoPartida(Integer idTipoPartida) {
		this.idTipoPartida = idTipoPartida;
	}

	@Column(name = "descricao", nullable = false, length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "qtdPartidas")
	public Integer getQtdPartidas() {
		return this.qtdPartidas;
	}

	public void setQtdPartidas(Integer qtdPartidas) {
		this.qtdPartidas = qtdPartidas;
	}

}
